import { locales, type Locale } from "@/i18n/config";

export const SITE_URL = (process.env.SITE_URL ?? "https://leomath.cn").replace(/\/$/, "");
export const SITE_NAME = "LeoMath";
/** Default share image, 1200 × 630, generated by scripts/make-icons.mjs. */
export const OG_IMAGE = { url: "/og.png", width: 1200, height: 630, alt: "LeoMath" };

export const ogLocale: Record<Locale, string> = { zh: "zh_CN", en: "en_US" };
export const htmlLang: Record<Locale, string> = { zh: "zh-CN", en: "en" };

/** hreflang map for a locale-independent path such as "/concepts/derivative" ("" for the home page). */
export function languageAlternates(path: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const l of locales) out[htmlLang[l]] = `/${l}${path}`;
  out["x-default"] = `/zh${path}`;
  return out;
}

export interface PageMetaInput {
  /** Page title without the site name; omit for the home page. */
  title?: string;
  description: string;
  type?: "website" | "article";
  /** Pages behind a login or holding a form: kept out of search results. */
  noindex?: boolean;
}

export interface PageMeta {
  /** The <title>: "Title · LeoMath", or "LeoMath — tagline" for the home page. */
  title: string;
  shareTitle: string;
  description: string;
  type: "website" | "article";
  noindex: boolean;
  /** Absolute URLs. */
  canonical: string;
  alternates: { hreflang: string; href: string }[];
  locale: Locale;
}

/** Canonical URL, hreflang alternates, Open Graph and Twitter card for one page; rendered by src/components/Head.astro. */
export function pageMeta(locale: Locale, path: string, tagline: string, { title, description, type = "website", noindex = false }: PageMetaInput): PageMeta {
  return {
    title: title ? `${title} · ${SITE_NAME}` : `${SITE_NAME} — ${tagline}`,
    shareTitle: title ? `${title} · ${SITE_NAME}` : SITE_NAME,
    description,
    type,
    noindex,
    canonical: `${SITE_URL}/${locale}${path}`,
    alternates: Object.entries(languageAlternates(path)).map(([hreflang, href]) => ({ hreflang, href: `${SITE_URL}${href}` })),
    locale,
  };
}
