import type { Metadata } from "next";
import { locales, type Locale } from "@/i18n/config";

export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://leomath.cn").replace(/\/$/, "");
export const SITE_NAME = "LeoMath";
/** Default share image, 1200 × 630, generated by scripts/make-icons.mjs. */
export const OG_IMAGE = { url: "/og.png", width: 1200, height: 630, alt: "LeoMath" };

const ogLocale: Record<Locale, string> = { zh: "zh_CN", en: "en_US" };

/** hreflang map for a locale-independent path such as "/concepts/derivative" ("" for the home page). */
export function languageAlternates(path: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const l of locales) out[l === "zh" ? "zh-CN" : l] = `/${l}${path}`;
  out["x-default"] = `/zh${path}`;
  return out;
}

interface PageMetaInput {
  /** Page title without the site name; omit for the home page. */
  title?: string;
  description: string;
  type?: "website" | "article";
  /** Pages behind a login or holding a form: kept out of search results. */
  noindex?: boolean;
}

/**
 * Canonical URL, hreflang alternates, Open Graph and Twitter card for one page.
 * Every page sets all of them, since Next.js replaces (not merges) openGraph and alternates from the layout.
 */
export function pageMeta(locale: Locale, path: string, { title, description, type = "website", noindex }: PageMetaInput): Metadata {
  const url = `/${locale}${path}`;
  const shareTitle = title ? `${title} · ${SITE_NAME}` : SITE_NAME;
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: url, languages: languageAlternates(path) },
    openGraph: {
      type,
      url,
      siteName: SITE_NAME,
      title: shareTitle,
      description,
      locale: ogLocale[locale],
      alternateLocale: locales.filter((l) => l !== locale).map((l) => ogLocale[l]),
      images: [OG_IMAGE],
    },
    twitter: { card: "summary_large_image", title: shareTitle, description, images: [OG_IMAGE.url] },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  };
}
